version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:19-alpine
    container_name: astrosite
    ports:
      - "1282:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: tail -f /dev/null

volumes:
  node_modules: {}